version: '3.1'

services:

    nginx:
        build: ./services/nginx/
        restart: always
        ports:
            - "80:80"
        volumes:
            - ${BACKEND_DIR}:/code
            - ./services/nginx/conf.d:/etc/nginx/conf.d
        links:
            - phpfpm
    phpfpm:
        build: ./services/phpfpm/
        working_dir: /code
        restart: always
        volumes:
            - ${BACKEND_DIR}:/code
        links:
            - mysqldb
            - postgresdb
    adminer:
        build: ./services/adminer/
        restart: always
        ports:
            - 8080:8080
        links:
            - mysqldb
            - postgresdb
    mysqldb:
        build: ./services/mysqldb/
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./services/mysqldb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./services/mysqldb/db_data:/var/lib/mysql
    postgresdb:
        build: ./services/postgresdb/
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./services/postgresdb/db_data:/var/lib/postgresql/data
    node:
        build: ./services/node/
        environment:
            - NODE_ENV=production
        working_dir: /code
        restart: "no"
        volumes:
            - ${FRONTEND_DIR}:/code
        command: ${NODE_COMMAND}
