version: '3.1'

services:

    nginx:
        build: ./services/nginx/
        ports:
            - ${NGINX_PORT_ON_HOST}:80
        volumes:
            - ${BACKEND_DIR}:/code
            - ./services/nginx/conf.d:/etc/nginx/conf.d
        links:
            - phpfpm
    phpfpm:
        build: ./services/phpfpm/
        working_dir: /code
        volumes:
            - ${BACKEND_DIR}:/code
        links:
            - mysqldb
            - postgresdb
        command: bash -c "bash -c \"${PHPFPM_COMMAND}\" && php-fpm"
    adminer:
        build: ./services/adminer/
        ports:
            - ${ADMINER_PORT_ON_HOST}:8080
        links:
            - mysqldb
            - postgresdb
    mysqldb:
        build: ./services/mysqldb/
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./services/mysqldb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
            - ./services/mysqldb/db_data:/var/lib/mysql
    postgresdb:
        build: ./services/postgresdb/
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./services/postgresdb/db_data:/var/lib/postgresql/data
    node:
        build: ./services/node/
        environment:
            - NODE_ENV=production
        working_dir: /code
        ports:
            - ${NODE_PORT}
        volumes:
            - ${FRONTEND_DIR}:/code
        command: bash -c "bash -c \"${NODE_COMMAND}\" && tail -f /dev/null"
