FROM php:7-fpm
#RUN apt-get update -y && apt-get install -y libpng-dev curl libcurl4-openssl-dev
#RUN docker-php-ext-install pdo pdo_mysql gd curl
#RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
